"""Changed seed data

Revision ID: b612c5655ca5
Revises: 1faa37ed287f
Create Date: 2024-02-14 22:05:50.002004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b612c5655ca5'
down_revision = '1faa37ed287f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
